### ISSUE TITLE
Addon won't enable

### ISSUE THREAD

**Issue by RocketSmash9000** [vaporvee/discord-sdk-godot#13]
So I extracted the addon to the addons folder of the project and it shows up in the plugins menu. Godot keeps erroring and disabling it because it couldn't be loaded.
![imagen_2023-05-10_173426137](https://github.com/vaporvee/discord-sdk-godot/assets/118481037/3c780864-a6cf-4765-9634-a8b4287be036)
Also, I'm using v3.5.2

**Comment by vaporvee** [comment]
Where did you download the plugin and wich version are you on? And sorry for asking but did you also put the addons folder on the root of your project?

**Comment by vaporvee** [comment]
Yeah sorry of course it only supports 4.x. Its based on gdextension wich only exists in 4.x. There is another plugin for an older version out there.

But you reminded me i should fix the bug that it only works on the project root
