### ISSUE TITLE
[Bug/Crash]: Error when exporting project

### ISSUE THREAD

**Issue by ItsAnysek** [vaporvee/discord-sdk-godot#20]
### What happened?

When exporting the project for the first time after loading into it, Godot gives an error message. After the first time this happens, it doesn't happen again when exporting until the project is reloaded. The exported game works fine.

I only tested this with the default Windows Desktop and Linux/X11 export presets, but it's possible that it happens with the rest of the presets as well.

### Also tell us, what did you expect to happen?

I expected to not get any errors when exporting.

### Version

1.5

### Godot Version

v4.0.2.stable.official [7a0977ce2]

### GDScript

```gdscript
# main scene file

func _ready():
	Discord_Activity.app_id = <my id>
	print("is discord working: " + str(Discord_Activity.get_is_discord_working()))
	Discord_Activity.details = "asdf"
	Discord_Activity.start_timestamp = int(Time.get_unix_time_from_system())
	Discord_Activity.refresh()
```

### Godot output

```shell
editor/export/editor_export_plugin.h:125 - Required virtual method EditorExportPlugin::_get_name must be overridden before calling.
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.

**Comment by ItsAnysek** [comment]
yes

**Comment by vaporvee** [comment]
The weird thing is ths is a normal godot function tatshould justwork but i'll try to fix it in 2.0

**Comment by vaporvee** [comment]
fixed in #21

**Comment by vaporvee** [comment]
Is in fact not fixed sorry but i found out the message only appears first time exporting

**Comment by ItsAnysek** [comment]
> but i found out the message only appears first time exporting

Didn't I state that in the issue?

**Comment by vaporvee** [comment]
Didn't see that

**Comment by ItsAnysek** [comment]
Ok. I mean if it doesn't break the whole addon and is just an annoying message it's fine.

**Comment by vaporvee** [comment]
when 2.0 releases let me know if it worked for you but for me its working
