### ISSUE TITLE
[Bug/Crash]: Addon could not update activity, Discord is running

### ISSUE THREAD

**Issue by V4NK0V** [vaporvee/discord-sdk-godot#32]
### What happened?

A bug happened!
Despite the fact that Discord is running, the game could not update activity for some reason. I've updated the addon but still no results. Few days or maybe even weeks ago everything was fine and I haven't load project until this day.

### Version

2.3

### Godot Version

4.0.3.stable

### GDScript

```gdscript
class_name DiscordSDKTutorial
extends Node

func _ready():
	discord_sdk.app_id = 1094211267742421082 # Application ID
	print("Discord working: " + str(discord_sdk.get_is_discord_working())) # A boolean if everything worked
	discord_sdk.details = "Launches the game"
	discord_sdk.state = ""
	
	discord_sdk.large_image = "hashiriyalogo" # Image key from "Art Assets"
	discord_sdk.large_image_text = "Try it now!"
	discord_sdk.small_image = "" # Image key from "Art Assets"
	discord_sdk.small_image_text = ""
	
	discord_sdk.start_timestamp = int(Time.get_unix_time_from_system()) # "02:41 elapsed"
	# Discord_Activity.end_timestamp = int(Time.get_unix_time_from_system()) + 3600 # +1 hour in unix time

	discord_sdk.refresh() # Always refresh after changing the values!
```

### Godot output

```shell
W 0:00:01:0627   discord_rich_presence.gd:18 @ _ready(): Discord Activity couldn't be updated. It could be that Discord isn't running!
  <Исходный код C++>core/variant/variant_utility.cpp:923 @ push_warning()
  <Трассировка стека>discord_rich_presence.gd:18 @ _ready()
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.

**Comment by vaporvee** [comment]
Okay first of all i don't recomend to just rewrite the tutorial one because it could be that the tutorial class exists twice now (but could be that it works lol) 
2.3 did just release a few days ago did you have this issue before you updated the plugin? And what do you mean with doesn't update? Does it show up at all and you just can't modify the Activity or is it not even showing up?

**Comment by vaporvee** [comment]
also why does `print("Discord working: " + str(discord_sdk.get_is_discord_working()))` not show up in your console log?

**Comment by V4NK0V** [comment]
The `print("Discord working: " + str(discord_sdk.get_is_discord_working()))` is showing in console, I just forgot to mention it in issue (not get used to working with github yet), it shows "false". And yes. the issue was before updating the plugin, also the demo project have same issue. Activity isn't showing up at all. I'm gonna paste the console log of console version of your built demo project 
`ERROR: Error loading GDExtension configuration file: res://ADDON-Discord-SDK-Godot/addons/discord-sdk-gd/discord-rpc-gd.gdextension
   at: load (core/extension/gdextension.cpp:509)
ERROR: Failed loading resource: res://ADDON-Discord-SDK-Godot/addons/discord-sdk-gd/discord-rpc-gd.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
ERROR: Error loading extension: res://ADDON-Discord-SDK-Godot/addons/discord-sdk-gd/discord-rpc-gd.gdextension
   at: (core/extension/gdextension_manager.cpp:120)
Godot Engine v4.0.2.stable.mono.official.7a0977ce2 - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

ERROR: .NET: Failed to load hostfxr
   at: (modules/mono/mono_gd/gd_mono.cpp:399)
WARNING: Discord Activity couldn't be updated. It could be that Discord isn't running!
     at: push_warning (core/variant/variant_utility.cpp:922)`

**Comment by vaporvee** [comment]
hm thats really weird it works for me and others perfectly well in the demo project. But i see there is a .NET error do you use the mono version of godot?

**Comment by V4NK0V** [comment]
No, I'm not using mono, but this is still weird. Maybe it's issue on Discord side? For like a week ago or more I got into "update failed" loop and only fix for this was copying updated discord folder from my friend pc. Maybe my discord installation including windows registry is corrupted in some way, that's the reason why addon could not "connect" to discord. I may try to reinstall discord completely from my pc later and then see if it works.

**Comment by vaporvee** [comment]
thats a good idea let me know how it went

**Comment by V4NK0V** [comment]
As I thought it was discord-side issue, I tried to reinstall discord properly but got no result, same "update failed" loop, then I've found public beta version installer and thankfully there was no issue with updating it, and now eveything works fine and the activity is updating. Even the problem was not in addon thanks for trying to help me out with it

**Comment by vaporvee** [comment]
👍
