### ISSUE TITLE
[Feature request]: Buttons 

### ISSUE THREAD

**Issue by holymode** [vaporvee/discord-sdk-godot#37]
### What is your idea?

Rich presence has ability to add 2 buttons that you can link stuff. Would be really useful to add.

**Comment by vaporvee** [comment]
This is not a feature in the Discord Game SDK it is possible with a forked version of the old discord-rpc repo. I tried some stuff in the branch called something with experimental if you want to make this work for yourself but it just didn't convert the strings from godot it cached them weirdly and its also extremely unstable...
