### ISSUE TITLE
[Bug]: Does not display RPC in Discord Client

### ISSUE THREAD

**Issue by zolrath** [vaporvee/discord-sdk-godot#43]
### What happened?

Hello!
While testing this plugin in Godot 4.2 RC2 this addon does not appear to work.
Editor Presence Enabled has no effect, nor does any Rich Presence I attempt to add to my own project.

### Version

3.2

### Godot Version

4.2-RC2

### GDScript

```gdscript
discord_sdk.app_id = myappid
discord_sdk.details = "Jumpin' on friends"
discord_sdk.state = "Playing %s" % GameManager.mode_info.name
discord_sdk.large_image = "bigbroccoli"
discord_sdk.large_image_text = "You're pretty cool!"
discord_sdk.start_timestamp = int(Time.get_unix_time_from_system())
discord_sdk.refresh()
```

### Godot output

```shell
No errors output
```

### Additional information

The DiscordSDKDebug node shows the values set but Discord does not register the game.
If I manually add the game to Discord a generic status is shown, but no Icon nor Rich Presence is shown.

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.

**Comment by vaporvee** [comment]
the plugin is made for 4.1. It will release a quick update once 4.2 is out.

**Comment by vaporvee** [comment]
still works with the current version but i will make a updated version soon
![grafik](https://github.com/vaporvee/discord-sdk-godot/assets/80621863/a9d902b3-fde5-4eae-aeb9-842d2f30f240)

**Comment by zolrath** [comment]
Tested with 4.2 as well just now and the Debug node displays the correct information, like you're showing for me but Discord does not pick up the Rich Presence. If I don't add the game manually nothing shows up in Discord, and if I add the executable myself it simply has a ?

![image](https://github.com/vaporvee/discord-sdk-godot/assets/454563/dbb6ad34-9205-4ce6-8bb0-fbc515cc8700)

```
	discord_sdk.app_id = myappidnotsureifthisshouldbeprivate
	discord_sdk.state = "Playing"
	discord_sdk.details = "Jumpin' on heads"
	discord_sdk.large_image = "bigbroccoli"
	discord_sdk.refresh()
```

**Comment by vaporvee** [comment]
yeah so it should work on 4.2 snd when the debug node shows up the correct information everything should work. maybe its your discord client? However maybe the update I'm working on right now will fix your issues

**Comment by vaporvee** [comment]
also did you remove the app id like in the debug node or is that normal for you?

**Comment by vaporvee** [comment]
oh i see

**Comment by vaporvee** [comment]
any updates?

**Comment by zolrath** [comment]
Ah so you can't reproduce the results? I don't see any updated version of this released so I haven't tried it again. Is there an updated build?

**Comment by vaporvee** [comment]
could you give me the completely exact steps you did?

**Comment by nemene21** [comment]
Same for me, making a thingy in godot 4.2, windows 10.
This is the debug scene, the app id and state are displayed correctly.
![image](https://github.com/vaporvee/discord-sdk-godot/assets/73829851/6875bb5a-f994-40c9-acc6-4ef2470395e6)
Buuuuuut, discord doesnt seem to register it :(
![image](https://github.com/vaporvee/discord-sdk-godot/assets/73829851/9290b73d-44f0-4bea-97ea-e55cb3b3ff11)

**Comment by vaporvee** [comment]
pushed an update tho
