### ISSUE TITLE
Discord does not show the application

### ISSUE THREAD

**Issue by nemene21** [vaporvee/discord-sdk-godot#45]
### What happened?

The debug scene displays correct information, but on discord it is now shown.

### Version

3.2

### Godot Version

4.2-stable_win64

### Exact steps to reproduce this error

Dowloaded the latest fix, extracted, went to the addons folder, added the addon in my addons folder, checked the addon checkbox to activate it, restarted godot, checked if the autoload was on, it was, wrote the code in an autoloaded script, opened the game

After I saw nothing was displayed on discord, I opened the debug scene which displayed the correct app id and state, but there was still nothing on the discord side of things.

Redowloaded plugin, redowloaded godot, redownloaded discord, issue persisted.

Discord -> settings -> Registered games:
![image](https://github.com/vaporvee/discord-sdk-godot/assets/73829851/35daf6b1-ae71-43bf-908b-453d6e4cdae3)

### GDScript

```gdscript
# Autoloaded script
func _ready() -> void:
	# TODO: Make this display actual info!
	discord_sdk.app_id = ****************** # Real app id matches the one on the discord developer portal
	discord_sdk.state = "In progress..."
	discord_sdk.refresh()
```

### Godot output

```shell
No output
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [x] I tried restarting Discord and Godot completely.

**Comment by vaporvee** [comment]
does the debug scene have a green circle? if it does and the discord_sdk.core_update() is in some _process() function (normaly in the autoload that got added) then it should work. otherwise the discord client or app_id can be the issue.

**Comment by vaporvee** [comment]
also it will be visible in your profile and not under registered games

**Comment by nemene21** [comment]
I added the discord_sdk.core_update call in a _process, but the editor says "Parser Error: Static function "core_update()" not found in base "GDScriptNativeClass"."

**Comment by vaporvee** [comment]
will be renamed to run_callbacks in the next update

**Comment by nemene21** [comment]
Added "discord_sdk.coreupdate()" in the autoload, still no luck.

Tried reinstalling the plugin in my project. There were many errors:
  core/extension/gdextension.cpp:884 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/discord-sdk-gd/discord-rpc-gd.gdextension
  Failed loading resource: res://addons/discord-sdk-gd/discord-rpc-gd.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/discord-sdk-gd/nodes/core_updater.gd:12 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/discord-sdk-gd/nodes/core_updater.gd" with error "Parse error". (User)
  gdscript://-9223369988692185208.gd:4 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:7 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:38 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:48 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:51 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:54 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:57 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223369988692185208.gd:63 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:27 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:28 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:29 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:30 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:31 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:32 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:33 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:34 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:35 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  res://addons/discord-sdk-gd/plugin.gd:36 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/discord-sdk-gd/plugin.gd" with error "Parse error". (User)

**Comment by vaporvee** [comment]
it basically says that you either didn't install the plugin correctly or didn't restart the engine.

**Comment by nemene21** [comment]
When I drag the plugin's folder into the addon folder it says this:
  gdscript://-9223307709569242234.gd:4 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:7 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:39 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:49 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:52 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:55 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:58 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:62 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:64 - Parse Error: Identifier "discord_sdk" not declared in the current scope.
  gdscript://-9223307709569242234.gd:67 - Parse Error: Identifier "discord_sdk" not declared in the current scope.

**Comment by nemene21** [comment]
I got the newest release and unzipped it, then dragged the folder into my addons folder, those were the errors.

**Comment by vaporvee** [comment]
yeah and i know what they mean. if you got these not declared errors the files might be in a wrong spot. could you install it from the in-editor asset library instead? then enable the plugin of course also in the project settings

**Comment by nemene21** [comment]
Did, I get the same errors.

**Comment by vaporvee** [comment]
make a fresh project, setup the plugin and send it to me. i cant reproduce

**Comment by nemene21** [comment]
Here you go, in this one it also says the scene "Debug.tscn" is corrupt when I try opening it.
[issue.zip](https://github.com/vaporvee/discord-sdk-godot/files/13638037/issue.zip)

**Comment by vaporvee** [comment]
yeah will look into it today. sorry that you need to wait I'm sick

**Comment by nemene21** [comment]
Don't rush it, stay safe, I can wait.

**Comment by vaporvee** [comment]
okay it says configuration/compatibility_minimum" key: res://addons/discord-sdk-gd/discord-rpc-gd.gdextension but it does... its 4.1. I started your project and anything works
![grafik](https://github.com/vaporvee/discord-sdk-godot/assets/80621863/7ce7f4f7-c872-4245-99f0-86793c718761)
so sadly it could be a discord client error. The new update will release soon though hope it fixes stuff.

**Comment by vaporvee** [comment]
but i pushed a update btw but you should maybe try the demo application in the wiki to check if its your client

**Comment by nemene21** [comment]
Sure, thanks for taking the time to help.
