### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by EddieDover** [vaporvee/discord-sdk-godot#47]
Firstly, thanks for the work involved in creating this plugin. I understand the immensity of it and I sincerely appreciate it.

I'm having an issue where the plugin doesn't seem to actually update my presence, There's no change to my status at all. If I enable the Project presence, then it shows I'm working in Godot, but after launching my game it remains the same. 

The Debug GUI element shows valid data and when I print my user dict with `print(DiscordSDK.get_current_user())` everything seems to be in order so it's definitely getting data from Discord. I even tried to manually call `run_callbacks()` even though the autoload was enabled, just to make sure it was happening.

What's the easiest way to verify that it's sending data to Discord? Is there some acknowledgement I can monitor?

OS: Windows 11

Also, I noticed this while disabling and enabling the plugin:
https://github.com/vaporvee/discord-sdk-godot/blob/e206b1184820ee1ee6e9eac5874b76718982ea4a/project/addons/discord-sdk-gd/plugin.gd#L29

"dully disable"

**Comment by vaporvee** [comment]
can you download the built demo and make sure it displays the demo activity? if not then its your discord client.

**Comment by EddieDover** [comment]
I'm not sure why but the issue was with the **party_id**.  If it's set to a single character string like "A" or "X" then the status never updated. However if I remove the setting completely or set it to something 2 or more characters long "AB" or "XY" or "abcd-efgh-ijkl-mnop" it worked fine.

**Comment by vaporvee** [comment]
good to know! will addvthat to the wiki soon thank you :)

**Comment by EddieDover** [comment]
@vaporvee Have you ever considered enabling Sponsorship for this repository?

**Comment by vaporvee** [comment]
yeah but i don't like stripe. but my kofi is linked :)

**Comment by vaporvee** [comment]
thank you so much <3
