### ISSUE TITLE
[Bug]: Rich Presence/Game not detected

### ISSUE THREAD

**Issue by zolrath** [vaporvee/discord-sdk-godot#48]
### What happened?

Hello!
The new version doesn't seem to have fixed my issues with discord failing to detect the game or Rich Presence.
I've now tested using your demo project and can confirm that it presents the issue as well.

### The game displays the information correctly.
![image](https://github.com/vaporvee/discord-sdk-godot/assets/454563/c00747d6-2ac9-4e89-9df5-943b79249ba6)
### In the console, the game knows who I am
![image](https://github.com/vaporvee/discord-sdk-godot/assets/454563/7fb5bb23-4634-44d3-9535-2f8c2317819f)
### Discord does not acknowledge the game
![image](https://github.com/vaporvee/discord-sdk-godot/assets/454563/987ca3e9-addb-4b49-b777-949603964f35)

I've uninstalled and reinstalled Discord to see if that has any effect, but it did not result in a change.

My OS is the most recent update of Windows 11:

OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631

### Version

1.0.0

### Godot Version

4.2.1

### Exact steps to reproduce this error

Run the demo project

### GDScript

```gdscript
Using the example GDScript causes this issue, but in this case no code is required as the compiled demo app shows the issue.
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://github.com/vaporvee/discord-sdk-godot/wiki

**Comment by zolrath** [comment]
I used the built demo linked from the wiki: https://github.com/vaporvee/discord-sdk-godot/releases/latest/download/Demo-Export.zip

**Comment by vaporvee** [comment]
I'm sorry but the demo works on any other machine. could be an issue with your discord client then. could you try reinstalling discord or make sure you didn't disable the activities in the privacy settings?

**Comment by EddieDover** [comment]
@zolrath Did you check your player-card to see if the rich presence was there? You only provided a screenshot of the registered games settings screen and it will not be displayed there afaik
![image](https://github.com/vaporvee/discord-sdk-godot/assets/464286/87cc34a9-08b0-4dcc-aa84-aa24d7682414)

**Comment by zolrath** [comment]
After resetting my settings I was able to get the rich presence to actually show up! 👍
Sorry for the false alarm and thanks for making this plugin!

**Comment by vaporvee** [comment]
no problem i know the best that discord can be weird sometimes 😅
